// Assignment Code
var generateBtn = document.querySelector("#generate");

let typeArr = [];

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}
console.log(typeArr)

// Add event listener to generate button

const generatePassword = () => {

  //this is asking the user through a prompt how many characters to include in the password

  const numChars = parseInt(prompt("How many characters would you like to have in your password? (8-128)"));

  console.log(numChars)

  //THIS CHECKS to see if the user entered between 8 and 128 in promptsif Na
  if(!isNaN(numChars) && numChars >= 8 && numChars < 129) {
    //The following will as if the user wants to include lower and upper case letters, special characters, and numbers

    const useLowerCase = confirm("Would you like your password to include Lowercase letters?");
    if (useLowerCase) {
      typeArr.push("lowerCase");
      console.log(typeArr)
      console.log(useLowerCase)
    }

    const useUpperCase = confirm("Would you like your password to include Uppercase letters?");
    if (useUpperCase) {
      typeArr.push("upperCase");
      console.log(typeArr)
      console.log(useUpperCase)
    }

    const useSpecialChars = confirm("Would you like your password to include any special characters?");
    if (useSpecialChars) {
      typeArr.push("specialChars");
      console.log(typeArr)
      console.log(useSpecialChars)
    }

    const useNumbers = confirm("Would you like your password to include any Numbers?");
    if (useNumbers) {
      typeArr.push("numbers");
      console.log(typeArr)
      console.log(useNumbers)
    }

    console.log(typeArr)

    let passwordText = "";

    console.log(passwordText)

    //following will loop i times where i is the user input for numChars (number of characters)

    for (i = 1; i <= numChars; i ++) {

      //The random part of the loop is generated by taking a random element of the array everytime it runs the loop

      const random = Math.floor(Math.random() * typeArr.length);
      //Numbers
      console.log(typeArr.length)
      console.log(random)
      
      if (typeArr[random] === "numbers") {

        myRandNum = randomNum(9);

        passwordText += myRandNum;

        console.log(passwordText)

        console.log(myRandNum)

        //Upper Case Letters
      } else if (typeArr[random] === "upperCase") {

        myRandUpperCase = randomLetter();

        myRandUpperCase = randomLetter().toUpperCase();

        passwordText += myRandUpperCase;
        
        console.log(passwordText)

        console.log(myRandUpperCase)

        //Lower Case Letters
      } else if (typeArr[random] === "lowerCase") {

        myRandLowerCase = randomLetter();

        passwordText += myRandLowerCase;

        console.log(passwordText)

        console.log(myRandLowerCase)

        //Special Characters
      } else if (typeArr[random] === "specialChars") {

        myRandSpecialChars = randomSpecialChars();

        passwordText += myRandSpecialChars;

        console.log(passwordText)

        console.log(myRandSpecialChars)

      }
      
    
    } 

    typeArr = []

    return passwordText;

  }

};

const randomNum = (max) => {
  return Math.floor(Math.random() * max);
}

function randomLetter() {
  const alphabet = "abcdefghijklmnopqrstuvwxyz"
  return alphabet[Math.floor(Math.random() * alphabet.length)];
}

function randomSpecialChars() {
  const specialChars = "!@#$%^&*_+"
  return specialChars[Math.floor(Math.random() * specialChars.length)];
}

generateBtn.addEventListener("click", writePassword);
